trigger:
- feature/*

pr:
- feature/*

resources:
- repo: self

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: SonarCloudAnalysis
  displayName: SonarCloud Analysis Stage
  jobs:
  - job: Analyze
    displayName: Run SonarCloud Analysis
    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self
      fetchDepth: 0

    - task: SonarCloudPrepare@3
      displayName: 'Prepare SonarCloud Analysis'
      inputs:
        SonarCloud: 'sdk_sonar'
        organization: 'fastpix'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'FastPix_react-native-uploader'
        cliProjectName: 'react-native-uploader'
        extraProperties: |
          sonar.projectKey=FastPix_react-native-uploader
          sonar.organization=fastpix
          sonar.projectName=react-native-uploader
          sonar.sources=.
          sonar.sourceEncoding=UTF-8

    # Install dependencies if required
    - script: |
        npm ci
      displayName: 'Install Dependencies'

    # Build the React Native project
    - script: |
        echo "Running build"
        npm run build || true
      displayName: 'Build Step'

    - task: SonarCloudAnalyze@3
      displayName: 'Run SonarCloud Code Analysis'

    - task: SonarCloudPublish@3
      displayName: 'Publish SonarCloud Quality Gate Results'
      inputs:
        pollingTimeoutSec: '300'